### ISSUE TITLE
Including cranium in more than one compilation unit results in compile errors

### ISSUE THREAD

**Issue by knome** [100/Cranium#1]
In order to support being used in more than one compilation unit in a C project ( including it in more than one .c file ), you need to apply the term "static" to all functions defined in the headers. I don't see any global data structures, which is good.

For example, given main.c of

    #include "cranium/cranium.h"
    
    int main( int argc, char ** argv ){
      return 0;
    }

and an other.c of

    #include "cranium/cranium.h"
    
    int otherfn( void ){
      return 4 ;
    }

you will receive a tirade of errors

    $ gcc main.c other.c -lm 2>&1 | head -20
    /tmp/ccuIMzd4.o: In function `createMatrix':
    other.c:(.text+0x0): multiple definition of `createMatrix'
    /tmp/ccpuiGmt.o:main.c:(.text+0x0): first defined here
    /tmp/ccuIMzd4.o: In function `createMatrixZeroes':
    other.c:(.text+0x72): multiple definition of `createMatrixZeroes'
    /tmp/ccpuiGmt.o:main.c:(.text+0x72): first defined here
    /tmp/ccuIMzd4.o: In function `createBatches':
    other.c:(.text+0x13b): multiple definition of `createBatches'
    /tmp/ccpuiGmt.o:main.c:(.text+0x13b): first defined here
    /tmp/ccuIMzd4.o: In function `copyValuesInto':
    other.c:(.text+0x226): multiple definition of `copyValuesInto'
    /tmp/ccpuiGmt.o:main.c:(.text+0x226): first defined here
    /tmp/ccuIMzd4.o: In function `printMatrix':
    other.c:(.text+0x2e3): multiple definition of `printMatrix'
    /tmp/ccpuiGmt.o:main.c:(.text+0x2e3): first defined here
    /tmp/ccuIMzd4.o: In function `zeroMatrix':
    other.c:(.text+0x382): multiple definition of `zeroMatrix'
    /tmp/ccpuiGmt.o:main.c:(.text+0x382): first defined here
    /tmp/ccuIMzd4.o: In function `transpose':
    other.c:(.text+0x3e4): multiple definition of `transpose'

etc.

**Comment by 100** [comment]
Thanks, just fixed this

**Comment by knome** [comment]
You missed createMatrixZeroes, for which you didn't provide a declaration, only the definition.

**Comment by 100** [comment]
whoops, added it in, thanks again
